# Generated by Django 4.1.3 on 2022-11-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('option1', models.CharField(max_length=120)),
                ('option2', models.CharField(max_length=120)),
                ('option3', models.CharField(max_length=120)),
                ('option4', models.CharField(max_length=120)),
                ('correct_option', models.CharField(max_length=120)),
                ('sheet', models.CharField(max_length=120)),
                ('file_name', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
